#!/bin/sh
cd ..
echo "BUILD_GOARCH: $BUILD_GOARCH"
echo "BUILD_GOOS: $BUILD_GOOS"
echo "SERVE_U: $SERVE_U"
echo "SERVE_R: $SERVE_R"
echo "DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "IMAGE_NAME: $IMAGE_NAME"
echo "QEMUARCH: $QEMUARCH"
docker run --rm --privileged multiarch/qemu-user-static:register
curl https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-${QEMUARCH}-static.tar.gz > x86_64_qemu-${QEMUARCH}-static.tar.gz
tar -xvf x86_64_qemu-${QEMUARCH}-static.tar.gz

if [ ${QEMUARCH} == 'amd64' ]; then
    sed -i "" "/__CROSS_/d" Dockerfile
else
    sed -i "" "s/__CROSS_//g" Dockerfile
fi
docker build --build-arg BUILD_GOARCH=$BUILD_GOARCH --build-arg BUILD_GOOS=$BUILD_GOOS --build-arg SERVE_U=$SERVE_U --build-arg SERVE_R=$SERVE_R --build-arg QEMUARCH=$QEMUARCH -f $DOCKERFILE_PATH -t $IMAGE_NAME .
