#!/bin/bash
cd ..

MULTIARCH_DOCKERFILE_PATH = $(sed -i "s/Dockerfile/multiarch.Dockerfile/")

cat ~/.docker/config.json
sed '2i "experimental": "enabled",' ~/.docker/config.json

docker run --rm --privileged multiarch/qemu-user-static:register

sed "/__MULTIARCH_/d" -o "$DOCKERFILE_PATH" "$MULTIARCH_DOCKERFILE_PATH"
docker build --build-arg BUILD_GOARCH="linux" --build-arg BUILD_GOOS="amd64" --build-arg SERVE_U="amd64" --build-arg SERVE_R="alpine" --build-arg QEMUARCH="amd64" -f "$DOCKERFILE_PATH" -t $(echo $IMAGE_NAME | sed "s/:latest/:amd64-latest/") .

sed "s/__MULTIARCH_//g" -o "$DOCKERFILE_PATH" "$MULTIARCH_DOCKERFILE_PATH"
curl -L "https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-i386-static.tar.gz" | tar xz
docker build --build-arg BUILD_GOARCH="linux" --build-arg BUILD_GOOS="386" --build-arg SERVE_U="i386" --build-arg SERVE_R="alpine" --build-arg QEMUARCH="i386" -f "$DOCKERFILE_PATH" -t $(echo $IMAGE_NAME | sed "s/:latest/:i386-latest/") .
curl -L "https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-arm-static.tar.gz" | tar xz
docker build --build-arg BUILD_GOARCH="linux" --build-arg BUILD_GOOS="arm" --build-arg SERVE_U="arm32v6" --build-arg SERVE_R="alpine" --build-arg QEMUARCH="arm" -f "$DOCKERFILE_PATH" -t $(echo $IMAGE_NAME | sed "s/:latest/:arm-latest/") .
curl -L "https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-aarch64-static.tar.gz" | tar xz
docker build --build-arg BUILD_GOARCH="linux" --build-arg BUILD_GOOS="arm64" --build-arg SERVE_U="arm64v8" --build-arg SERVE_R="alpine" --build-arg QEMUARCH="aarch64" -f "$DOCKERFILE_PATH" -t $(echo $IMAGE_NAME | sed "s/:latest/:aarch64-latest/") .
curl -L "https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-ppc64le-static.tar.gz" | tar xz
docker build --build-arg BUILD_GOARCH="linux" --build-arg BUILD_GOOS="ppc64le" --build-arg SERVE_U="ppc64le" --build-arg SERVE_R="alpine" --build-arg QEMUARCH="ppc64le" -f "$DOCKERFILE_PATH" -t $(echo $IMAGE_NAME | sed "s/:latest/:ppc64le-latest/") .
curl -L "https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-s390x-static.tar.gz" | tar xz
docker build --build-arg BUILD_GOARCH="linux" --build-arg BUILD_GOOS="s390x" --build-arg SERVE_U="s390x" --build-arg SERVE_R="alpine" --build-arg QEMUARCH="s390x" -f "$DOCKERFILE_PATH" -t $(echo $IMAGE_NAME | sed "s/:latest/:s390x-latest/") .
