#!/bin/sh
docker run --rm --privileged multiarch/qemu-user-static:register
wget -N https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-${QEMUARCH}-static.tar.gz
tar -xvf x86_64_qemu-${QEMUARCH}-static.tar.gz

if [ ${QEMUARCH} == 'amd64' ]; then
    sed "" "/__CROSS_/d" Dockerfile.template > Dockerfile
else
    sed "" "s/__CROSS_//g" Dockerfile.template > Dockerfile
fi
