#!/bin/bash
if [ "${QEMUARCH}" == 'amd64' ]
then
    sed -i "/__CROSS_/d" $DOCKERFILE_PATH
else
    docker run --rm --privileged multiarch/qemu-user-static:register
    curl -L "https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/x86_64_qemu-${QEMUARCH}-static.tar.gz" | tar xz
    sed -i "s/__CROSS_//g" $DOCKERFILE_PATH
fi
